### ISSUE TITLE
"Read Minecraft Tips!" Button redirects to 404 Error page.

### ISSUE THREAD

**Issue by SNGTech** [IngeniousApplications/IAWEB-Issue#31] opened 2020-05-24 08:56 UTC
**Describe the bug**
The "Read our Minecraft Tips!" button redirects to an IA Gaming 404 Error page.

**URL OF FAULTY SITE**
https://gaming.ingeniousapps.net/g/tips

**Expected behavior**
It should redirect to the Minecraft Tips site.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Microsoft Edge

https://i.gyazo.com/453f7dba90faa246ee6b4014c4239efa.png

**Comment by IngeniousCoder** [comment] 2020-05-24 09:03
duplicate of #28

**Closed by IngeniousCoder** 2020-05-24 09:03 UTC
